apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: terraform-controller
  namespace: vela-system
spec:
  components:
    - name: terraform-controller
      type: helm
      properties:
        repoType: "helm"
        url: "https://kubevela.github.io/charts/"
        chart: "terraform-controller"
        values:
          terraformImage: "ghcr.io/activa-prefapp/docker-terraform:1.5.5"