apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: provision-vpc-sample
  namespace: default
spec:
  components:
    - name: activaprefapp-sample-vpc
      type: aws-vpc-aws-orig
      properties:
        source: "aws-ia/vpc/aws"
        version: ">= 4.2.0"
        name: "multi-az-vpc"
        cidr_block: "10.0.0.0/16"
        vpc_assign_generated_ipv6_cidr_block: true
        vpc_egress_only_internet_gateway: true
        az_count: 3
        subnets:
          public:
            name_prefix: "my_public"
            netmask: 24
            assign_ipv6_cidr: true
            nat_gateway_configuration: "all_azs"
          private:
            netmask: 24
            connect_to_public_natgw: true
          private_ipv6:
            ipv6_native: true
            assign_ipv6_cidr: true
            connect_to_eigw: true
        writeConnectionSecretToRef:
          name: vpc-conn
        providerRef:
          name: aws3
