apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/description: Authentication solution that allows users to log in to multiple applications and websites with a single user authentication
  creationTimestamp: null
  labels:
    type: terraform
  name: aws-sso
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: https://github.com/prefapp/tfm.git
      path: modules/aws-sso
      providerRef:
        name: aws
        namespace: default
      type: remote
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta1
      kind: Configuration
status: {}